### ISSUE TITLE
Fail to load nerd font

### ISSUE THREAD

**Issue by Jisu-Woniu** [easterNday/easterNday.github.io#5]
![图片](https://user-images.githubusercontent.com/31986081/236176077-85975f80-fdb4-4451-ab6e-c57e7ce2ca12.png)

If I access the page manually, I get the error message:

![图片](https://user-images.githubusercontent.com/31986081/236176389-b65a0247-0490-4290-b4c0-870c65eb844a.png)

**Comment by easterNday** [comment]
Thank you very much for helping me discover an error. I attempted to use a resource that no longer existed, which caused the error to occur. After checking, I realized that the resource was no longer available, so I switched to another Nerd Font and the problem was resolved. I truly appreciate your assistance, and your guidance has taught me a great deal.

**Comment by Jisu-Woniu** [comment]
The favicon.ico is still missing.

**Comment by easterNday** [comment]
You are right, I will set this part in a follow-up update, thanks for the reminder.
